[build-system]
requires = [
    "setuptools>=58.0.4",
    "build>=0.7.0",
    "astropy==5.3.1",
    "bokeh==3.2.0",
    "click==8.0.4",
    "dask==2021.10.0",
    "matplotlib==3.4.3",
    "numpy==1.22.3",
    "photutils==1.8.0"
]
build-backend = "setuptools.build_meta"

